apps/vend/urls.py
from django.urls import path
from . import views


app_name = "vend"
urlpatterns = [
    path('setup/vendgroup/', views.VendGroupListView.as_view(), name="vendgroup"),
    path('setup/vendgroup/create/', views.VendGroupCreateView.as_view(), name="vendgroup-create"),
    path('setup/vendgroupjson/', views.VendGroup_Json.as_view(), name="vendgroup-json"),
    path('setup/vendgroup/<int:pk>/update/', views.VendGroupUpdateView.as_view(), name="vendgroup-update"),
    path('setup/vendgroup/<int:pk>/delete/', views.VendGroupDeleteView.as_view(), name="vendgroup-delete"),
    path('vendtable/', views.VendTableListView.as_view(), name="vendtable"),
    path('vendtable/create/', views.VendTableCreateView.as_view(), name="vendtable-create"),
    path('vendtable/<int:pk>/update/', views.VendTableUpdateView.as_view(), name="vendtable-update"),
    path('vendtablejson/', views.VendTable_Json.as_view(), name="vendtable-json"),
    path('vendtable/<int:pk>/delete/', views.VendTableDeleteView.as_view(), name="vendtable-delete"),
    path('vendtable/vendaddress/<int:vendtable_id>/create/', views.VendAddressCreateView.as_view(), name="vendaddress-create"),
    path('vendtable/vendaddress/<int:pk>/update/', views.VendAddressUpdateView.as_view(), name="vendaddress-update"),
    path('vendtable/vendaddress/<int:pk>/delete/', views.VendAddressDeleteView.as_view(), name="vendaddress-delete"),
    path('vendtable/vendaddress/<int:pk>/', views.VendAddressDetailView.as_view(), name="vendaddress-detail"),
    path('vendtable/vendcontact/<int:vendtable_id>/create/', views.VendContactCreateView.as_view(), name="vendcontact-create"),
    path('vendtable/vendcontact/<int:pk>/update/', views.VendContactUpdateView.as_view(), name="vendcontact-update"),
    path('vendtable/vendcontact/<int:pk>/delete/', views.VendContactDeleteView.as_view(), name="vendcontact-delete"),
    path('vendtable/vendcontact/<int:pk>/', views.VendContactDetailView.as_view(), name="vendcontact-detail"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", include("apps.authentication.urls")), # Auth routes - login / register
    path('', include('authentication.urls')),
    path('', include('home.urls')),
    path('system/', include('system.urls')),
    path('basic/', include('basic.urls')),
    path('hrm/', include('hrm.urls')),
    path('ledger/', include('ledger.urls')),
    path('invent/', include('invent.urls')),
    path('vend/', include('vend.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handling the 404 error
handler404 = "system.views.error_404_view"

handler500 = "system.views.error_500_view"

handler403 = "system.views.error_403_view"

apps/basic/models.py
from django.db import models
from django.utils.translation import get_language, gettext_lazy as _
from system.models import Language
from django.core.exceptions import ObjectDoesNotExist


class CountryRegion(models.Model):
    code = models.CharField(max_length=2, unique=True, verbose_name=_('Country/region'))
    name = models.CharField(max_length=250)
    en_name = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('english name'))

    def __str__(self):
        return  "(%s) %s" % (self.code,self.name)


class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True, verbose_name=_('currency'))
    name = models.CharField(max_length=60)
    symbol = models.CharField(max_length=5, null=True, blank=True)

    def __str__(self):
        return  self.code


class CompanyInfo(models.Model):
    name = models.CharField(max_length=60, unique=True, verbose_name=_('company name'))
    en_name = models.CharField(max_length=60, null=True, blank=True, verbose_name=_('english name'))
    taxnum = models.CharField(max_length=18, null=True, blank=True, verbose_name=_('tax number'))
    address = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('address'))
    zipcode = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('Postal code'))
    countryregion = models.ForeignKey('CountryRegion', on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_('Country/region'))
    language = models.ForeignKey('system.Language', on_delete=models.SET_NULL, null=True, blank=True)
    currency = models.ForeignKey('Currency', on_delete=models.SET_NULL, null=True, blank=True)
    telephone = models.CharField(max_length=40, null=True, blank=True)
    telephoneext = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('extension'))
    teleFax = models.CharField(max_length=40, null=True, blank=True)
    mobilephone = models.CharField(max_length=40, null=True, blank=True, verbose_name="mobile phone")
    email = models.EmailField(null=True, blank=True)
    url = models.URLField(null=True, blank=True, verbose_name="web site")

    def __str__(self):
        return self.name


class CompanyAddress(models.Model):
    NONE = "N"
    DELIVERY = "D"
    INVOICE = "I"
    PAYMENT = "P"
    OTHER = "O"
    TYPE_CHOICES = [
        (NONE, _('none')),
        (DELIVERY, _('delivery')),
        (INVOICE, _('invoice')),
        (PAYMENT, _('payment')),
        (OTHER, _('other')),
    ]

    company =  models.ForeignKey('CompanyInfo', on_delete=models.CASCADE)
    name = models.CharField(max_length=60, unique=True, verbose_name=_('name'))
    addresstype = models.CharField(max_length=2, choices=TYPE_CHOICES, default=NONE, null=True, blank=True, verbose_name=_('address type'))
    address = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('address'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("person title")
    

class Unit(models.Model):
    unit_id = models.CharField(max_length=5, unique=True, verbose_name=_("unit"))
    txt = models.CharField(_("name"), max_length=30, blank=True)
    unit_decimals = models.PositiveSmallIntegerField(_("decimals"), default=2)
    symbol = models.CharField(max_length=5, null=True, blank=True)

    class Meta:
        verbose_name = _("units")

    
    def __str__(self):
        return  self.unit_id

    
    def language_unit(self, unitid, languageid=get_language()):
        language = Language.objects.get(code=languageid)
        
        try:
            unit_txt = UnitTxt.objects.get(unit=self.id,language=language)
            return unit_txt.unitid_txt
        except ObjectDoesNotExist:
            return unitid


class UnitTxt(models.Model):
    unit = models.ForeignKey("Unit", on_delete=models.CASCADE)
    language = models.ForeignKey('system.Language', on_delete=models.SET_NULL, null=True, blank=True)
    unitid_txt = models.CharField(_("text"), max_length=10, blank=True)

    class Meta:
        verbose_name = _("unit texts")
        unique_together = ["unit", "language"]
    
    def __str__(self):
        return  self.unitid_txt


class UnitConvert(models.Model):
    HALF_UP = "O"
    UP = "U"
    DOWN = "D"
    ROUND_CHOICES = [
        (HALF_UP, _('round off')),
        (UP, _('up')),
        (DOWN, _('down')),
    ]

    from_unit = models.ForeignKey("Unit", on_delete=models.RESTRICT, blank=True, verbose_name=_("from unit"), related_name="from_unit")
    to_unit = models.ForeignKey("Unit",  on_delete=models.RESTRICT, blank=True, verbose_name=_("to unit"), related_name="to_unit")
    factor = models.DecimalField(max_digits=9, decimal_places=5)
    markup = models.DecimalField(_("additional quantity"), default=0, max_digits=5, decimal_places=2)
    round_off =  models.CharField(max_length=2, choices=ROUND_CHOICES, default=HALF_UP, verbose_name=_('round-off'))

    class Meta:
        verbose_name = _("unit conversion")
        unique_together = ["from_unit", "to_unit"]

    def __str__(self):
        return  self.from_unit.unit_id

     #JSON
    def get_data(self):
        return {
            'id': self.id,
            'from_unit': self.from_unit.unit_id,
            'to_unit': self.to_unit.unit_id,
            'factor': self.factor,
            'markup': self.markup,
            'round_off': self.get_round_off_display()
        }


class NumberSequenceTable(models.Model):
    number_code = models.CharField(_("number sequence code"), max_length=10, unique=True)
    txt = models.CharField(_("name"), max_length=30, blank=True)
    lowest = models.PositiveIntegerField(_("smallest"), default=1)
    highest = models.PositiveIntegerField(_("largest"))
    next_rec = models.PositiveIntegerField(_("next"), blank=True)
    num_format = models.CharField(_("format"), max_length=30, blank=True)

    class Meta:
        verbose_name = _("number sequence")

    def __str__(self):
        return self.number_code


""" Distribution models """
class DlvTerm(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Delivery terms"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    class Meta:
        verbose_name = _("Terms of delivery")

    def __str__(self):
        return self.code


class DlvMode(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Delivery Mode"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    class Meta:
        verbose_name = _("Mode of delivery")

    def __str__(self):
        return self.code

    
class DlvDestination(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Destination code"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    class Meta:
        verbose_name = _("Destination of delivery")

    def __str__(self):
        return self.code
        

apps/vend/models/basic.py
from django.db import models
from django.utils.translation import get_language, gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.utils import translation
from django.conf import settings

from basic.models import Unit, Currency, CountryRegion, DlvTerm, DlvMode, DlvDestination
from ledger.models import TaxGroupHeading, PaymTerm
from system.models import Language
from hrm.models import Employee
from utils.common_field import AddressType
from django.urls import reverse


class VendGroup(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Vendor group"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Name"))

    class Meta:
        verbose_name = _("Vendor groups")

    def __str__(self):
        return self.code


class VendTable(models.Model):
    account_num = models.CharField(max_length=20, unique=True, verbose_name=_('Account'))
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    short_name = models.CharField(max_length=60, null=True, blank=True, verbose_name=_('Short name'))
    invoice_account = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, verbose_name="Invoice account")
    vend_group = models.ForeignKey(VendGroup, on_delete=models.RESTRICT, null=True, blank=True)
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, blank=True)
    countryregion = models.ForeignKey(CountryRegion, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_('Country/region'))
    url = models.URLField(null=True, blank=True, verbose_name="Internet address")
    main_contact = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Main contact"))
    dlv_term = models.ForeignKey(DlvTerm, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Terms of delivery"))
    dlv_mode = models.ForeignKey(DlvMode, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Mode of delivery"))
    dlv_destination = models.ForeignKey(DlvDestination, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Destination of delivery"))
    paym_term = models.ForeignKey(PaymTerm, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Terms of payment"))
    tax_group = models.ForeignKey(TaxGroupHeading, on_delete=models.RESTRICT, blank=True, null=True)
    incl_tax = models.BooleanField(_("Prices incl. sales tax"), default=True, help_text=_("Do prices include sales tax?"))
    notes = models.TextField(_("notes"), null=True, blank=True)
    blocked = models.BooleanField(_("Stopped"), default=False, help_text=_("Is the account locked?"))
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="creater", verbose_name=_("Created by"))
    created_dt = models.DateTimeField(auto_now_add=True, verbose_name=_("Created date time"))
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="modifieder", verbose_name=_("Last modified by"))
    lastmodified_dt = models.DateTimeField(auto_now=True, verbose_name=_("Last modified date time"))


    class Meta:
        verbose_name = _("Vendors")

    def __str__(self):
        return f'{self.account_num} | {self.short_name}' 


class VendAddress(models.Model):
    vendtable = models.ForeignKey(VendTable, on_delete=models.CASCADE, verbose_name=_('Vend account'))
    name = models.CharField(max_length=60, verbose_name=_('name'))
    is_primary = models.BooleanField(_("Primary"), help_text=_("Primary address for address book record."))
    addresstype = AddressType()
    address = models.TextField(max_length=250, null=True, blank=True, verbose_name=_('Address'))
    zipcode = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('Postal code'))
    city = models.CharField(max_length=30, null=True, blank=True, verbose_name=_('City'))
    state = models.CharField(max_length=30, null=True, blank=True, verbose_name=_('State'))
    countryregion = models.ForeignKey(CountryRegion, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_('Country/region'))

    class Meta:
        unique_together = ["vendtable", "name"]
        verbose_name = _("Vendor addresses")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this address."""
        return reverse('vend:vendaddress-detail', args=[str(self.id)])

    # def clean(self):
    #     data = self.is_primary
    #     print(data)
    #     if data:
    #         raise ValidationError(
    #             {"is_primary": _("You have forgotten about Fred!")}
    #         )

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        

class VendContact(models.Model):
    vendtable = models.ForeignKey(VendTable, on_delete=models.CASCADE, verbose_name=_('Vend account'))
    is_primary = models.BooleanField(_("Primary"))
    name = models.CharField(max_length=60, unique=True, verbose_name=_('Contact'))
    telephone = models.CharField(max_length=40, null=True, blank=True)
    telephoneext = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('Extension'))
    teleFax = models.CharField(max_length=40, null=True, blank=True, verbose_name=_("Fax"))
    mobilephone = models.CharField(max_length=40, null=True, blank=True, verbose_name=_("Mobile phone"))
    email = models.EmailField(null=True, blank=True, verbose_name=_("E-mail"))
    
    class Meta:
        verbose_name = _("Vendor contact")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this address."""
        return reverse('vend:vendcontact-detail', args=[str(self.id)])
    

apps/vend/forms.py
from django.forms import ModelForm, TextInput, HiddenInput, Textarea
from django.forms import inlineformset_factory
from .models.basic import VendTable, VendAddress, VendContact
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


class VendAddressForm(ModelForm):
    class Meta:
        model = VendAddress
        fields = ['vendtable',"name",'is_primary',"addresstype","address",'zipcode','city','state','countryregion']

    def clean_is_primary(self):
        vendtable_id = self.cleaned_data["vendtable"]
        is_primary = self.cleaned_data["is_primary"]

        if is_primary:
            if VendAddress.objects.filter(vendtable=vendtable_id,is_primary=True).count():
                raise ValidationError(_("Only one primary address is allowed per address book record."))

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return is_primary


class VendContactForm(ModelForm):
    class Meta:
        model = VendContact
        fields = ['vendtable',"name",'is_primary',"telephone","telephoneext",'teleFax','mobilephone','email']

    def clean_is_primary(self):
        vendtable_id = self.cleaned_data["vendtable"]
        is_primary = self.cleaned_data["is_primary"]

        if is_primary:
            if VendContact.objects.filter(vendtable=vendtable_id,is_primary=True).count():
                raise ValidationError(_("Only one primary contact is allowed per contact."))

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return is_primary

templates/vend/vendtable_update.html
{% load i18n widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" id="details-form" class="needs-validation" novalidate> 
  <div class="tab-pane fade" id="general-tab-pane" role="tabpanel" aria-labelledby="general-tab" tabindex="0">
    <fieldset class="row g-3 mb-4">
      <legend>{% translate 'Identification' %}</legend>
      <div class="col-4">
        <label for="{{ form.account_num.id_for_label }}" class="form-label">{{ form.account_num.label_tag }}</label>
        {% render_field form.account_num class="form-control" readonly="readonly" %}
        <div class="invalid-feedback">{{ form.account_num.errors|first }}</div>
      </div>
      <div class="col-md-8">
        <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label_tag }}</label>
        {% render_field form.name class="form-control" autocomplete="off" %}
        <div class="invalid-feedback">{{ form.name.errors|first }}</div>
      </div>
      <div class="col-md-4">
        <label for="{{ form.short_name.id_for_label }}" class="form-label">{{ form.short_name.label_tag }}</label>
        {% render_field form.short_name class="form-control" autocomplete="off" %}
        <div class="invalid-feedback">{{ form.short_name.errors|first }}</div>
      </div>
      <div class="col-md-6">
        <label for="{{ form.blocked.id_for_label }}" class="form-label">{{ form.blocked.label_tag }}</label>
        <div class="mb-3 form-check form-switch">
        <label for="{{ form.blocked.id_for_label }}" class="form-check-label">{{ form.blocked.help_text }}</label>
        {% render_field form.blocked class="form-check-input form-control" role="switch" %}
        </div>
        <div class="invalid-feedback">{{ form.blocked.errors|first }}</div>
      </div>
    </fieldset>
    <fieldset class="row g-3 mb-4">
      <legend>{% translate 'Vender' %}</legend>
      <div class="col-md-4">
        <label for="{{ form.vend_group.id_for_label }}" class="form-label">{{ form.vend_group.label_tag }}</label>
        {% render_field form.vend_group class="form-control" %}
        <div class="invalid-feedback">{{ form.vend_group.errors|first }}</div>
      </div>
      <div class="col-md-4">
        <label for="{{ form.currency.id_for_label }}" class="form-label">{{ form.currency.label_tag }}</label>
        {% render_field form.currency class="form-control" %}
        <div class="invalid-feedback">{{ form.currency.errors|first }}</div>
      </div>
      <div class="col-md-4">
        <label for="{{ form.language.id_for_label }}" class="form-label">{{ form.language.label_tag }}</label>
        {% render_field form.language class="form-control" %}
        <div class="invalid-feedback">{{ form.language.errors|first }}</div>
      </div>
      <div class="col-md-4">
        <label for="{{ form.countryregion.id_for_label }}" class="form-label">{{ form.countryregion.label_tag }}</label>
        {% render_field form.countryregion class="form-control" %}
        <div class="invalid-feedback">{{ form.countryregion.errors|first }}</div>
      </div>
      <div class="col-md-4">
        <label for="{{ form.main_contact.id_for_label }}" class="form-label">{{ form.main_contact.label_tag }}</label>
        {% render_field form.main_contact class="form-control select2" %}
        <div class="invalid-feedback">{{ form.main_contact.errors|first }}</div>
      </div>
      <div class="col-md-4">
        <label for="{{ form.url.id_for_label }}" class="form-label">{{ form.url.label_tag }}</label>
        {% render_field form.url class="form-control" %}
        <div class="invalid-feedback">{{ form.url.errors|first }}</div>
      </div>
      <div class="col-md-12">
        <label for="{{ form.notes.id_for_label }}" class="form-label">{{ form.notes.label_tag }}</label>
        {% render_field form.notes class="form-control" rows="3" %}
        <div class="invalid-feedback">{{ form.notes.errors|first }}</div>
      </div>
      <div class="col-md-3">
        <label for="id_created_by" class="form-label">{% translate "Created by" %}</label>
        <input type="text" readonly class="form-control-plaintext" value="{{ vendtable.created_by }}">
      </div>
      <div class="col-md-3">
        <label class="form-label">{% translate "Created date time" %}:</label>
        <input type="text" readonly class="form-control-plaintext" value="{{ vendtable.created_dt }}">
      </div>
      <div class="col-md-3">
        <label for="id_modified_by" class="form-label">{% translate "Last modified by" %}</label>
        <input type="text" readonly class="form-control-plaintext" value="{{ vendtable.modified_by }}">
      </div>
      <div class="col-md-3">
        <label class="form-label">{% translate "Last modified date time" %}:</label>
        <input type="text" readonly class="form-control-plaintext" value="{{ vendtable.lastmodified_dt }}">
      </div>
    </fieldset>
  </div>
  <div class="tab-pane fade" id="setup-tab-pane" role="tabpanel" aria-labelledby="setup-tab" tabindex="0">
    <div class="row g-3">
      <fieldset class="col">
        <legend>{% translate 'Invoice' %}</legend>
        <div class="mb-3">
          <label for="{{ form.invoice_account.id_for_label }}" class="form-label">{{ form.invoice_account.label_tag }}</label>
          {% render_field form.invoice_account class="form-control select2" %}
          <div class="invalid-feedback">{{ form.invoice_account.errors|first }}</div>
        </div>
      </fieldset>
      <fieldset class="col">
        <legend>{% translate 'Delivery' %}</legend>
        <div class="mb-3">
          <label for="{{ form.dlv_term.id_for_label }}" class="form-label">{{ form.dlv_term.label_tag }}</label>
          {% render_field form.dlv_term class="form-control" %}
          <div class="invalid-feedback">{{ form.dlv_term.errors|first }}</div>
        </div>
        <div class="mb-3">
          <label for="{{ form.dlv_mode.id_for_label }}" class="form-label">{{ form.dlv_mode.label_tag }}</label>
          {% render_field form.dlv_mode class="form-control" %}
          <div class="invalid-feedback">{{ form.dlv_mode.errors|first }}</div>
          <div class="form-text">{{ form.dlv_mode.help_text }}</div>
        </div>
        <div class="mb-3">
          <label for="{{ form.dlv_destination.id_for_label }}" class="form-label">{{ form.dlv_destination.label_tag }}</label>
          {% render_field form.dlv_destination class="form-control" %}
          <div class="invalid-feedback">{{ form.dlv_destination.errors|first }}</div>
          <div class="form-text">{{ form.dlv_destination.help_text }}</div>
        </div>
      </fieldset>
      <fieldset class="col">
        <legend>{% translate 'Payment' %}</legend>
        <div class="mb-3">
          <label for="{{ form.paym_term.id_for_label }}" class="form-label">{{ form.paym_term.label_tag }}</label>
          {% render_field form.paym_term class="form-control" %}
          <div class="invalid-feedback">{{ form.paym_term.errors|first }}</div>
          <div class="form-text">{{ form.paym_term.help_text }}</div>
        </div>
        <div class="mb-3">
          <label for="{{ form.tax_group.id_for_label }}" class="form-label">{{ form.tax_group.label_tag }}</label>
          {% render_field form.tax_group class="form-control" %}
          <div class="invalid-feedback">{{ form.tax_group.errors|first }}</div>
          <div class="form-text">{{ form.tax_group.help_text }}</div>
        </div>
        <div class="mb-3">
          <label for="{{ form.incl_tax.id_for_label }}" class="form-label">{{ form.incl_tax.label_tag }}</label>
          <div class="form-check form-switch">
          <label for="{{ form.incl_tax.id_for_label }}" class="form-check-label">{{ form.incl_tax.help_text }}</label>
          {% render_field form.incl_tax class="form-check-input form-control" role="switch" %}
          </div>
          <div class="invalid-feedback">{{ form.is_active.errors|first }}</div>
        </div>
      </fieldset>
    </div>
  </div>
  <div class="tab-pane fade" id="address-tab-pane" role="tabpanel" aria-labelledby="address-tab" tabindex="0">
    {% if perms.vend.add_vendaddress %}
    <div class="d-flex justify-content-between">
      <div class="p-2">{{ vendtable.account_num }} | {{ vendtable.name }}</div>
      <a hx-get="{% url 'vend:vendaddress-create' vendtable.id %}" class="btn btn-primary btn-sm mb-2" hx-target="#comaddressform" hx-swap="beforebegin"
      data-toggle="tooltip" data-bs-placement="top" data-bs-title={% translate 'New' %}>
        <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
      </a>
    </div>
    {% endif %}
    {% if perms.vend.view_vendaddress %}
    <div id="comaddressform">
    {% for vendaddress in vendtable.vendaddress_set.all %}
      {% include "vend/vendaddress_detail.html" %}
    {% endfor %}
    {% endif %}
    </div>
  </div>
  <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">
    {% if perms.vend.add_vendcontact %}
    <div class="d-flex justify-content-between">
      <div class="p-2">{{ vendtable.account_num }} | {{ vendtable.name }}</div>
      <a hx-get="{% url 'vend:vendcontact-create' vendtable.id %}" class="btn btn-primary btn-sm mb-2" hx-target="#contactform" hx-swap="beforebegin"
      data-toggle="tooltip" data-bs-placement="top" data-bs-title={% translate 'New' %}>
        <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
      </a>
    </div>
    {% endif %}
    {% if perms.vend.view_vendcontact %}
    <div id="contactform">
    {% for vendcontact in vendtable.vendcontact_set.all %}
      {% include "vend/vendcontact_detail.html" %}
    {% endfor %}
    {% endif %}
    </div>
  </div>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end p-2 d-none">
      <button type="submit" class="btn btn-primary d-none" id="btnsubmit">{% translate 'Submit' %}</button>
  </div>
</form>
{% endwith %}
<script>
// show form after page refreshed
$(function() {
  var activeTab = $(".nav-link.active").attr('data-bs-target');
  //alert(activeTab);
  $(".tab-pane").not(activeTab).addClass('d-none')
  $(activeTab).addClass("active show");

  $( '.select2' ).select2({
    theme: "bootstrap-5",
    width: "100%",
  });
})

</script>