apps/system/urls.py
from django.urls import path
from . import views
from authentication.views import UserCreateView

app_name = "system"
urlpatterns = [
    path('', views.IndexView.as_view(), name='system'),
    path('starter', views.starterView.as_view(), name='starter'),
    path('language/', views.LanguageListView.as_view(), name="language"),
    path('language/create/', views.LanguageCreateView.as_view(), name="language-create"),
    path('languagejson/', views.LanguageList_Json.as_view(), name="language-json"),
    path('langjson/', views.Language_Json.as_view(), name="langinfojson"),
    path('language/<int:pk>/update/', views.LanguageUpdateView.as_view(), name="language-update"),
    path('language/<int:pk>/delete/', views.LanguageDeleteView.as_view(), name="language-delete"),
    path('menu/', views.MenuListView.as_view(), name="menu"),
    path('menu/create/', views.MenuCreateView.as_view(), name="menu-create"),
    path('menujson/', views.MenuList_Json.as_view(), name="menu-json"),
    path('menu/<int:pk>/update/', views.MenuUpdateView.as_view(), name="menu-update"),
    path('menu/<int:pk>/delete/', views.MenuDeleteView.as_view(), name="menu-delete"),
    path('menu/<int:pk>/langtext/', views.manage_menulangname, name="menu-langText"),
    path('permission/', views.PermissionistView.as_view(), name="permission"),
    path('permissionjson/', views.PermissionList_Json.as_view(), name="permission-json"),
    path('permission/create/', views.PermissionCreateView.as_view(), name="permission-create"),
    path('permission/<int:pk>/update/', views.PermissionUpdateView.as_view(), name="permission-update"),
    path('permission/<int:pk>/delete/', views.PermissionDeleteView.as_view(), name="permission-delete"),
    path('session/', views.SessionListView.as_view(), name="session"),
    path('sessionjson/', views.SessionList_Json.as_view(), name="session-json"),
    path('session/<str:pk>/delete/', views.SessionDeleteView.as_view(), name="session-delete"),
    path('session/delete/<str:pks>', views.delete_SessionView.as_view(), name="delete-session"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", include("apps.authentication.urls")), # Auth routes - login / register
    path('', include('authentication.urls')),
    path('', include('home.urls')),
    path('system/', include('system.urls')),
    path('basic/', include('basic.urls')),
    path('hrm/', include('hrm.urls')),
    path('ledger/', include('ledger.urls')),
    path('invent/', include('invent.urls')),
    path('vend/', include('vend.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handling the 404 error
handler404 = "system.views.error_404_view"

handler500 = "system.views.error_500_view"

handler403 = "system.views.error_403_view"

apps/system/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.translation import activate, get_language_info, get_language
from django.contrib.auth.models import Permission
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist


class EmptyModel(models.Model):
    pass


# Create your models here.
class Language(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Code"))
    description = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    def __str__(self):
        return "(%s) %s" % (self.code,self.description)

    def display_name(self):
        li = get_language_info(self.code)
        return  f'{li["name_local"]}'

    #JSON
    def get_data(self):
        return {
            'id': self.id,
            'code': self.code,
            'description': self.description,
        }


class Menu(models.Model):
    NAVBAR = 'N'
    SIDEBAR = 'S'
    TYPE_CHOICES = [
        (NAVBAR, 'Navbar'),
        (SIDEBAR, 'Sidebar'),
    ]
    name = models.CharField(max_length=30, verbose_name="Name")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, verbose_name="Parent Id")
    url = models.CharField(max_length=128, null=True, blank=True)
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name="Icon")
    menutype = models.CharField(max_length=2, null=True, blank=True, choices=TYPE_CHOICES, default=SIDEBAR) 
    permission = models.ForeignKey('auth.Permission', on_delete=models.SET_NULL, null=True, blank=True)
    seq = models.FloatField(null=True, blank=True, verbose_name="Order")
    is_home = models.BooleanField(default=False, verbose_name="Home")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    created_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["name", "parent"]
        ordering = ["seq"]

    def __str__(self):
        if self.parent:
            return f'{self.parent}|{self.name}'
        else:
            return self.name

    def menu_perms(self):
        """Perms for menu on the template."""
        return "%s.%s" % (self.permission.content_type.app_label, self.permission.codename)

    def menutxt(self):
        lang_code = get_language()
        try:
            Lang = Language.objects.get(code=lang_code)
            menu_txt = MenuLangName.objects.get(menuid=self.id, lang=Lang)
            return menu_txt.name
        except ObjectDoesNotExist:
            return self.name
            

class MenuLangName(models.Model):
    menuid = models.ForeignKey('Menu', on_delete=models.CASCADE)
    lang  = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=30, verbose_name="Name")

    class Meta:
        unique_together = ["menuid", "lang"]

    def __str__(self):
        return self.name

apps/system/forms.py
from django.forms import inlineformset_factory
from .models import Menu, MenuLangName

MenuLangNameFormset = inlineformset_factory(
    Menu, MenuLangName, fields=["lang", "name"], extra=1, can_delete=True
)

apps/system/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy, resolve
from django.utils.translation import gettext, gettext_lazy as _
from .models import Language, Menu, MenuLangName
from django.utils.translation import get_language_info
from django.core.exceptions import ValidationError
from django.core import serializers
from django.contrib.auth.models import Permission
from django.contrib import messages
from django.contrib.sessions.models import Session
from django.contrib.sessions.backends.db import SessionStore
from django.utils import timezone

# Create your views here.
import datetime
import json
import zoneinfo

User = get_user_model()

#Handle error page
def error_404_view(request, exception):  
    return render(request, 'system/errors/404.html')


def error_500_view(request):  
    return render(request, 'system/errors/500.html')


def error_403_view(request, exception):  
    return render(request, 'system/errors/403.html')


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        # match  = resolve(request.path_info)
        # print(request.path_info)
        # print(match.url_name)
        # print(match.app_name)
        # print(match.view_name)
        menu_nav = Menu.objects.filter(menutype="N")
        menu_top = menu_nav.get(url="system:system")
        menu_side = Menu.objects.filter(parent = menu_top)
        menu_home = menu_side.filter(is_home=True)[0]

        context = {
            'menu_nav': menu_nav,
            'menu_side': menu_side,
            'menu_home': menu_home,
        }
        return render(request, 'home/ihome.html', context=context)


class starterView(LoginRequiredMixin, View):
    def get(self, request):
        #sessions = Session.objects.iterator() # also works with Session.objects.get_queryset()
        sessions = Session.objects.filter(expire_date__gte=timezone.now())
        for session in sessions: # iterate over sessions
            data = session.get_decoded() # decode the session data
            data["session_key"] = session.session_key
            data["expire_date"] = session.expire_date # normally the data doesn't include the session key, so add it
            #print(data)

        #print(request.session.get("django_timezone"))
        match  = resolve(request.path_info)
        # print(match.url_name)
        # print(match.app_name)
        # print(match.view_name)
        menu_nav = Menu.objects.filter(menutype="N")
        menu_home = menu_nav.get(name="System")
        menu_side = Menu.objects.filter(parent = menu_home)

        context = {
            'menu_nav': menu_nav,
            'menu_side': menu_side,
            'menu_home': menu_home,
        }
        return render(request, 'system/starter.html', context=context)


class LanguageListView(PermissionRequiredMixin, generic.ListView):
    model = Language
    template_name = "system/language_list.html"
    permission_required = "system.view_language"

    def get_context_data(self, **kwargs):
        # for key, value in self.request.session.items():
        #     print('{} => {}'.format(key, value))

        # Call the base implementation first to get the context
        context = super(LanguageListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        #context['some_data'] = self.request.session.get('_auth_user_backend','default')
        context['some_data'] = self.request.META.get("REMOTE_ADDR")
        return context


class Language_Json(PermissionRequiredMixin, View):
    permission_required = "system.view_language"

    def get(self, reqeust, *args, **kwargs):
        code=str(reqeust.GET['code'])
        data = {}
        error_msg = {}
        if code:
            try:
                data = get_language_info(code)
            except KeyError as ke:
                error_msg = {'errmsg': f'{ke}'}

        #print(error_msg)
        Langs = {'data':data,'msg':error_msg}
        return JsonResponse(Langs)


class LanguageList_Json(PermissionRequiredMixin, View):
    permission_required = "system.view_language"

    def get(self, reqeust):
        Langs = Language.objects.all()
        data = [lang.get_data() for lang in Langs]
        response = {'data': data}
        return JsonResponse(response)


class LanguageCreateView(PermissionRequiredMixin, CreateView):
    model = Language
    fields = '__all__'
    template_name = "system/language_form.html"
    success_url = reverse_lazy('system:language')
    permission_required = "system.add_language"

    def form_valid(self, form):
        super().form_valid(form)
        msg = _("Language %(name)s created") % {"name": form.instance.code}
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "reloadTable": None,
                    "showMessage": f'{msg}'
                })
            })


class LanguageUpdateView(PermissionRequiredMixin, UpdateView):
    model = Language
    fields = '__all__'
    template_name = "system/language_form.html"
    success_url = reverse_lazy('system:language')
    permission_required = "system.change_language"

    def form_valid(self, form):
        super().form_valid(form)
        msg = _("Language %(name)s updated") % {"name": form.instance.code}
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "reloadTable": None,
                    "showMessage": f'{msg}'
                })
            })


class LanguageDeleteView(PermissionRequiredMixin, DeleteView):
    model = Language
    template_name = "system/language_delete.html"
    success_url = reverse_lazy('system:language')
    permission_required = "system.delete_language"
    
    def form_valid(self, form):
        # s = SessionStore(session_key="ipzwklmuvacwufbgyrojfml0k5elve1e")
        # s.delete()
        super().form_valid(form)
        msg = _("Language %(name)s deleted") % {"name": self.object}
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "reloadTable": None,
                    "showMessage": f'{msg}'
                })
            })


class MenuListView(PermissionRequiredMixin, generic.ListView):
    model = Menu
    context_object_name = "menu_list"
    template_name = "system/menu_list.html"
    permission_required = "system.view_menu"


class MenuList_Json(PermissionRequiredMixin, View):
    permission_required = "system.view_menu"

    def get(self, reqeust):
        menu = Menu.objects.all()
        fields = ['id', 'icon', 'is_home', 'menutype', 'name', 'parent', 'parent__name','permission__codename', 'seq', 'url']
        #print(Menu.objects.values(*fields))
        ret = dict(data=list(Menu.objects.values(*fields)))
        return JsonResponse(ret)


class MenuCreateView(PermissionRequiredMixin, CreateView):
    model = Menu
    fields = '__all__'
    template_name = "system/Menu_form.html"
    success_url = reverse_lazy('system:menu')
    permission_required = "system.add_menu"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        super().form_valid(form)
        msg = _("Menu item %(name)s created") % {"name": form.instance.name}
        #print(msg)
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "reloadTable": None,
                    "showMessage": f'{msg}'
                })
            })


class MenuUpdateView(PermissionRequiredMixin, UpdateView):
    model = Menu
    fields = ['icon', 'is_home', 'menutype', 'name', 'parent','permission', 'seq', 'url']
    template_name = "system/menu_form.html"
    success_url = reverse_lazy('system:menu')
    permission_required = "system.change_menu"

    def form_valid(self, form):
        super().form_valid(form)
        msg = _("Menu %(name)s updated") % {"name": form.instance.name}
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "reloadTable": None,
                    "showMessage": f'{msg}'
                })
            })


class MenuDeleteView(PermissionRequiredMixin, DeleteView):
    model = Menu
    template_name = "system/menu_delete.html"
    success_url = reverse_lazy('system:menu')
    permission_required = "system.delete_menu"
    
    def form_valid(self, form):
        super().form_valid(form)
        msg = _("Menu %(name)s deleted") % {"name": self.object}
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "reloadTable": None,
                    "showMessage": f'{msg}'
                })
            })


from .forms import MenuLangNameFormset
def manage_menulangname(request, pk):
    # author = get_object_or_404(Author, pk=pk)
    menu = Menu.objects.get(pk=pk)
    #BookInlineFormSet = inlineformset_factory(Author, Book, fields=('title','genre','language',),can_delete=True)
    if request.method == "POST":
        formset = MenuLangNameFormset(request.POST, request.FILES, instance=menu)
        if formset.is_valid():
            formset.save()
            # Do something. Should generally end with a redirect. For example:
            #return HttpResponseRedirect(reverse_lazy('system:menu'))
            msg = _("Menu text of %(name)s updated") % {"name": menu.name}
            #print(msg)
            return HttpResponse(

templates/system/language_delete.html
{% load i18n %}
<form hx-post="{{ request.path }}" class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title"><i class="fa-solid fa-trash-can"></i>&nbsp;&nbsp;{% blocktranslate with object_t=object %} Delete {{ object_t }} {% endblocktranslate %}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
     <p class="delete-text">{% translate 'Are you sure you want to delete ' %}
      <strong>{{ language }}</strong>?</p>
  </div>
  <div class="modal-footer flex-nowrap p-0">
    <button type="submit" class="btn btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">{% translate 'Confirm' %}</button>
    <button type="button" class="btn btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" data-bs-dismiss="modal">
      {% translate 'Cancel' %}
    </button>
  </div>
</form>

templates/system/language_form.html
{% load i18n widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" class="modal-content shadow-none" style="max-height: 100%; height: 100%;">
  <div class="offcanvas-header border-bottom">
    <h5 class="offcanvas-title"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;
    {% translate 'Language' as title %}
    {% if object %} {% blocktranslate with object_t=object %} Edit {{ object_t }} {% endblocktranslate %} {% else %} {% blocktranslate %} Add {{ title }} {% endblocktranslate %} {% endif %} </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="mb-3">
      <label for="{{ form.code.id_for_label }}" class="form-label">{% translate 'Code' %}</label>
      {% render_field form.code class="form-control" onchange="showdata()" %}
      <div class="invalid-feedback">{{ form.code.errors|first }}</div>
      <div id="id_msg" class="invalid-feedback"></div>
    </div>
    <div class="mb-3">
      <label for="{{ form.description.id_for_label }}" class="form-label">{% translate 'Description' %}</label>
      {% render_field form.description|remove_attr:"required" class="form-control" autocomplete="off" %}
      <div class="invalid-feedback">{{ form.description.errors|first }}</div>
    </div>
  </div>
  <div class="d-flex justify-content-end border-top p-2 align-items-center">
    <button type="button" class="btn btn-secondary me-2" data-bs-dismiss="offcanvas">{% translate 'Cancel' %}</button>
    <button type="submit" class="btn btn-primary">{% translate 'Submit' %}</button>
  </div>
</form>
{% endwith %}

templates/system/language_list.html
{% extends "layouts/base-datatable.html" %}
{% load i18n %}
{% load static %}

{% block stylesheets %}
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->
{% endblock stylesheets %}

{% block navigation %}
<nav class="navbar navbar-expand-sm fixed-top bg-light border shadow-sm rounded">
  <div class="container-fluid">
    <ul class="navbar-nav col-sm-6">
      {% if perms.system.add_language %}
      <li class="nav-item">
        <a hx-get="{% url 'system:language-create' %}" accesskey="N" class="btn btn-sm btn-light nav-link" data-bs-toggle="offcanvas" hx-target="#offcanvas" 
        data-toggle="tooltip" data-bs-placement="bottom" data-bs-title= "New (Alt+N)">
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
        </a>
      </li>
      {% endif %}
      {% if perms.system.change_language %}
      <li class="nav-item">
        <button type="button" id="btnEdit" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Edit' %} disabled>
          <i class="fa-solid fa-pen"></i>&nbsp;&nbsp;{% translate 'Edit' %}
        </button>
      </li>
      {% endif %}
      {% if perms.system.delete_language %}
      <li class="nav-item">
        <button type="button" id="btnDel" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Delete' %} disabled>
          <i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;{% translate 'Delete' %}
        </button>
      </li>
      {% endif %}
    </ul>
    <div class="col-sm-6 d-flex justify-content-end">
      <div class="btn-group" role="group" aria-label="related function">
      </div>
    </div>
  </div>
</nav>
{% endblock navigation %}

{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            {% translate 'Language' %}
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="LangList" class="table table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                    <th>{% translate 'code' %}</th>
                    <th>{% translate 'Description' %}</th>
                  </tr>
              </thead>
            </table>
          </div> <!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>

    <!-- /.content -->
  </div>

  <!-- Placeholder for the offcanvas -->
  <div id="offcanvas" class="offcanvas offcanvas-end" aria-labelledby="offcanvasLabel" hx-target="this">
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>

{% endblock content %}  

{% block javascripts %}
<script>
$(document).ready(function(){    
  table = new DataTable('#LangList',{
      ajax: "{% url 'system:language-json' %}",
      columns: [
          { data: 'code' },
          { data: 'description' },
      ],
      rowId: 'id',
      select: {
          style: 'single'
      },
      colReorder: true,
      "initComplete": function( settings, json ) {
                    htmx.process('#LangList');
      },
  });

  table
    .on('select', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').removeAttr("disabled");
    })
    .on('deselect', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').attr("disabled", "disabled");
    });

  document.body.addEventListener("reloadTable", function(evt){
    table.ajax.reload(function() {
        htmx.process('#LangList');
    }, false)
  });
  
  $("#btnEdit").click(function () {    
      var id = table.row({ selected: true }).id();
      doUpdate(id);
  });
  $("#btnDel").click(function () {    
      var id = table.row({ selected: true }).id();
      doDelete(id);
  });
  $("#btnrefresh").click(function () {    
      table.ajax.reload();
  });
})
</script>
<script>
function showdata() {
  var code = document.getElementById("id_code").value;
  $.get( "{% url 'system:langinfojson' %}", { code: code } )
    .done(function( data ) {
      if (Object.keys(data.data).length === 0) {
        $("#id_code").addClass("is-invalid");
        $('#id_msg').append(data.msg.errmsg);
        $('#id_description').val('');
        $("#id_code").focus();
      } else {
        $("#id_code").removeClass("is-invalid");
        $('#id_description').val(data.data.name_local);
      }
  });
}

function doUpdate(id) {
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'system:language-update' 123 %}".replace(/123/, id.toString()), {target:'#offcanvas', swap:'innerHTML'});
}
function doDelete(id) {
  //window.location.href = "{% url 'group-delete' 123 %}".replace(/123/, id.toString())
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'system:language-delete' 123 %}".replace(/123/, id.toString()), {target:'#dialog', swap:'innerHTML'});
}
</script>
{% endblock javascripts %}

templates/system/permission_list.html
{% extends "layouts/base-datatable.html" %}
{% load i18n %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'dist/plugins/select2/css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/plugins/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css' %}">
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->
  <!-- datatable selected rows -->
{% endblock stylesheets %}

{% block navigation %}
<nav class="navbar navbar-expand-sm fixed-top bg-light border shadow-sm rounded">
  <div class="container-fluid">
    <ul class="navbar-nav col-sm-6">
      {% if perms.auth.add_Permission %}
      <li class="nav-item">
        <a hx-get="{% url 'system:permission-create' %}" class="btn btn-sm btn-light nav-link" data-bs-toggle="offcanvas" hx-target="#offcanvas" 
        data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'New' %}>
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
        </a>
      </li>
      {% endif %}
      {% if perms.authentication.change_permission %}
      <li class="nav-item">
        <button type="button" id="btnEdit" class="btn btn-light  btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Edit' %} disabled>
          <i class="fa-solid fa-pen"></i>&nbsp;&nbsp;{% translate 'Edit' %}
        </button>
      </li>
      {% endif %}
      {% if perms.authentication.delete_permission %}
      <li class="nav-item">
        <button type="button" id="btnDel" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Delete' %} disabled>
          <i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;{% translate 'Delete' %}
        </button>
      </li>
      {% endif %}
    </ul>
    <div class="col-sm-6 d-flex justify-content-end">
      <button class="btn btn-primary btn-sm">Button</button>
    </div>
  </div>
</nav>
{% endblock navigation %}

{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            {% translate 'Permission' %}
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="tableList" class="table table-sm table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                    <th>{% translate 'Content Type' %}</th>
                    <th>{% translate 'Model' %}</th>
                    <th>{% translate 'Code Name' %}</th>
                    <th>{% translate 'Name' %}</th>
                  </tr>
              </thead>
            </table>
          </div><!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>

    <!-- /.content -->
  </div>

  <!-- Placeholder for the offcanvas -->
  <div id="offcanvas" class="offcanvas offcanvas-end" aria-labelledby="offcanvasLabel" hx-target="this">
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>

{% endblock content %}  

{% block javascripts %}
<script src="{% static 'dist/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'dist/plugins/select2/js/select2.min.js' %}"></script>
<script>
$(document).ready(function(){    
  table = new DataTable('#tableList',{
      ajax: "{% url 'system:permission-json' %}",
      columns: [
          { data: 'content_type__app_label' },
          { data: 'content_type__model' },
          { data: 'codename' },
          { data: 'name' },
      ],
      columnDefs: [
        {
            render: (data, type, row) => data + ' | ' + row.content_type__model,
            targets: 0
        },
        { visible: false, targets: [1] }
      ],
      rowId: 'id',
      select: {
          style: 'single'
      },
      colReorder: true,
      "initComplete": function( settings, json ) {
                    htmx.process('#tableList');
      },
  });
  
  table
    .on('select', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').removeAttr("disabled");
    })
    .on('deselect', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').attr("disabled", "disabled");
    });

  document.body.addEventListener("reloadTable", function(evt){
    table.ajax.reload(function() {
        htmx.process('#tableList');
    }, false)
  });
  
  $("#btnEdit").click(function () {    
      var id = table.row({ selected: true }).id();
      doUpdate(id);
  });
  $("#btnDel").click(function () {
      var id = table.row({ selected: true }).id();
      doDelete(id);
  });
})
</script>
<script>
function doUpdate(id) {
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'system:permission-update' 123 %}".replace(/123/, id.toString()), {target:'#offcanvas', swap:'innerHTML'});
}
function doDelete(id) {
  //window.location.href = "{% url 'group-delete' 123 %}".replace(/123/, id.toString())
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'system:permission-delete' 123 %}".replace(/123/, id.toString()), {target:'#dialog', swap:'innerHTML'});
}
</script>
{% endblock javascripts %}