apps/ledger/urls.py
from django.urls import path
from . import views


app_name = "ledger"
urlpatterns = [
    path('setup/taxtable/', views.TaxTableListView.as_view(), name="taxtable"),
    path('setup/taxtable/create/', views.TaxTableCreateView.as_view(), name="taxtable-create"),
    path('setup/taxtablejson/', views.TaxTable_Json.as_view(), name="taxtable-json"),
    path('setup/taxtable/<int:pk>/update/', views.TaxTableUpdateView.as_view(), name="taxtable-update"),
    path('setup/taxtable/<int:pk>/delete/', views.TaxTableDeleteView.as_view(), name="taxtable-delete"),
    path('setup/taxgroupheading/', views.TaxGroupHeadingListView.as_view(), name="taxgroupheading"),
    path('setup/taxgroupheading/create/', views.TaxGroupHeadingCreateView.as_view(), name="taxgroupheading-create"),
    path('setup/taxgroupheadingjson/', views.TaxGroupHeading_Json.as_view(), name="taxgroupheading-json"),
    path('setup/taxgroupheading/<int:pk>/update/', views.TaxGroupHeadingUpdateView.as_view(), name="taxgroupheading-update"),
    path('setup/taxgroupheading/<int:pk>/delete/', views.TaxGroupHeadingDeleteView.as_view(), name="taxgroupheading-delete"),
    path('setup/taxitemgroupheading/', views.TaxItemGroupHeadingListView.as_view(), name="taxitemgroupheading"),
    path('setup/taxitemgroupheading/create/', views.TaxItemGroupHeadingCreateView.as_view(), name="taxitemgroupheading-create"),
    path('setup/taxitemgroupheadingjson/', views.TaxItemGroupHeading_Json.as_view(), name="taxitemgroupheading-json"),
    path('setup/taxitemgroupheading/<int:pk>/update/', views.TaxItemGroupHeadingUpdateView.as_view(), name="taxitemgroupheading-update"),
    path('setup/taxitemgroupheading/<int:pk>/delete/', views.TaxItemGroupHeadingDeleteView.as_view(), name="taxitemgroupheading-delete"),
    path('setup/paymterm/', views.PaymTermListView.as_view(), name="paymterm"),
    path('setup/paymterm/create/', views.PaymTermCreateView.as_view(), name="paymterm-create"),
    path('setup/paymtermjson/', views.PaymTerm_Json.as_view(), name="paymterm-json"),
    path('setup/paymterm/<int:pk>/update/', views.PaymTermUpdateView.as_view(), name="paymterm-update"),
    path('setup/paymterm/<int:pk>/delete/', views.PaymTermDeleteView.as_view(), name="paymterm-delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", include("apps.authentication.urls")), # Auth routes - login / register
    path('', include('authentication.urls')),
    path('', include('home.urls')),
    path('system/', include('system.urls')),
    path('basic/', include('basic.urls')),
    path('hrm/', include('hrm.urls')),
    path('ledger/', include('ledger.urls')),
    path('invent/', include('invent.urls')),
    path('vend/', include('vend.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handling the 404 error
handler404 = "system.views.error_404_view"

handler500 = "system.views.error_500_view"

handler403 = "system.views.error_403_view"

apps/ledger/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from basic.models import Currency
# Create your models here.


class TaxTable(models.Model):
    HALF_UP = "O"
    UP = "U"
    DOWN = "D"
    ROUND_CHOICES = [
        (HALF_UP, _('round off')),
        (UP, _('up')),
        (DOWN, _('down')),
    ]

    code = models.CharField(max_length=10, unique=True, verbose_name=_("Tax code"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Name"))
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True, blank=True)
    roundoff = models.FloatField(_("Round-off"), default=0.01, help_text=_('Special rounding-off for VAT'))
    roundoff_type =  models.CharField(max_length=2, choices=ROUND_CHOICES, default=HALF_UP, verbose_name=_('Rounding form'))
    value = models.FloatField(help_text=_('Percentage or amount per unit'))

    class Meta:
        verbose_name = _("VAT codes")

    def __str__(self):
        return self.code

    #JSON
    def get_data(self):
        str_cur = '' if self.currency is None else self.currency.code

        return {
            'id': self.id,
            'code': self.code,
            'name': self.name,
            'currency': str_cur,
            'roundoff': self.roundoff,
            'roundoff_type': self.get_roundoff_type_display(),
            'value': self.value
        }
    


class TaxGroupHeading(models.Model):
    tax_group = models.CharField(max_length=10, unique=True, verbose_name=_("Tax group"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Name"))
    tax_code = models.ManyToManyField(TaxTable)

    class Meta:
        verbose_name = _("Tax group")

    def __str__(self):
        return self.tax_group

    def display_tax(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(tax_code.code for tax_code in self.tax_code.all()[:3])

    display_tax.short_description = 'Tax'

    #JSON
    def get_data(self):
        return {
            'id': self.id,
            'tax_group': self.tax_group,
            'name': self.name,
            'display_tax': self.display_tax(),
        }


class TaxItemGroupHeading(models.Model):
    tax_item_group = models.CharField(max_length=10, unique=True, verbose_name=_("Item tax group"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Name"))
    tax_code = models.ManyToManyField(TaxTable)

    class Meta:
        verbose_name = _("Item tax group")

    def __str__(self):
        return self.tax_item_group

    def display_tax(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(tax_code.code for tax_code in self.tax_code.all()[:3])

    display_tax.short_description = 'Tax'

    #JSON
    def get_data(self):
        return {
            'id': self.id,
            'tax_item_group': self.tax_item_group,
            'name': self.name,
            'display_tax': self.display_tax(),
        }


""" PaymTerm """
class PaymTerm(models.Model):
    NET = "N"
    MONTH = "M"
    QUART = "Q"
    YEAR = "Y"
    WEEK = "Y"
    COD = "C"
    METHOD_CHOICES = [
        (NET, _('Net')),
        (MONTH, _('Curr.Mth.')),
        (QUART, _('Curr.Qtr.')),
        (YEAR, _('Curr.Year')),
        (WEEK, _('Curr.Week')),
        (COD, _('C.O.D.')),
    ]

    code = models.CharField(max_length=10, unique=True, verbose_name=_("Payment terms"))
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    paym_method =  models.CharField(max_length=2, choices=METHOD_CHOICES, default=NET, verbose_name=_('Payment method'))
    num_of_months = models.PositiveSmallIntegerField(_("Months"), default=0, help_text=_("Number of months past the specified method of payment")) 
    num_of_weeks = models.PositiveSmallIntegerField(_("Weeks"), default=0, help_text=_("Number of weeks past the specified method of payment"))
    num_of_days = models.PositiveSmallIntegerField(_("Days"), default=0, help_text=_("Number of days past the specified method of payment")) 


    class Meta:
        verbose_name = _("Terms of payment")

    def __str__(self):
        return self.code

    #JSON
    def get_data(self):
        return {
            'id': self.id,
            'code': self.code,
            'name': self.name,
            'paym_method': self.get_paym_method_display(),
            'num_of_months': self.num_of_months,
            'num_of_weeks': self.num_of_weeks,
            'num_of_days': self.num_of_days,
        }

apps/ledger/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib import messages

from .models import TaxTable, TaxGroupHeading, TaxItemGroupHeading, PaymTerm
from utils import custom

import json


class TaxTableListView(PermissionRequiredMixin, generic.ListView):
    model = TaxTable
    template_name = "ledger/taxtable_list.html"
    permission_required = "ledger.view_taxtable"


class TaxTable_Json(custom.JSONResponseMixin):
    permission_required = "ledger.view_taxtable"

    def get(self, request):
        taxtable = TaxTable.objects.all()
        data = [d.get_data() for d in taxtable]
        ret = {'data': data}
        return JsonResponse(ret)


class TaxTableCreateView(custom.ObjectCreateView):
    model = TaxTable
    fields = '__all__'
    success_url = reverse_lazy('ledger:taxtable')
    permission_required = "ledger.add_taxtable"
    title = model._meta.verbose_name


class TaxTableUpdateView(custom.ObjectUpdateView):
    model = TaxTable
    fields = '__all__'
    success_url = reverse_lazy('ledger:taxtable')
    permission_required = "ledger.change_taxtable"
    title = model._meta.verbose_name


class TaxTableDeleteView(custom.ObjectDeleteView):
    model = TaxTable
    success_url = reverse_lazy('ledger:taxtable')
    permission_required = "ledger.delete_taxtable"
    title = model._meta.verbose_name


class TaxGroupHeadingListView(PermissionRequiredMixin, generic.ListView):
    model = TaxGroupHeading
    template_name = "ledger/taxgroupheading_list.html"
    permission_required = "ledger.view_taxgroupheading"


class TaxGroupHeading_Json(custom.JSONResponseMixin):
    permission_required = "ledger.view_taxgroupheading"

    def get(self, request):
        taxgroup = TaxGroupHeading.objects.all()
        data = [d.get_data() for d in taxgroup]
        ret = {'data': data}
        return JsonResponse(ret)


class TaxGroupHeadingCreateView(custom.ObjectCreateView):
    model = TaxGroupHeading
    fields = '__all__'
    success_url = reverse_lazy('ledger:taxgroupheading')
    permission_required = "ledger.add_taxgroupheading"
    title = model._meta.verbose_name


class TaxGroupHeadingUpdateView(custom.ObjectUpdateView):
    model = TaxGroupHeading
    fields = '__all__'
    success_url = reverse_lazy('ledger:taxgroupheading')
    permission_required = "ledger.change_taxgroupheading"
    title = model._meta.verbose_name
    template_name = "common/offcanvas_form.html"


class TaxGroupHeadingDeleteView(custom.ObjectDeleteView):
    model = TaxGroupHeading
    success_url = reverse_lazy('ledger:taxgroupheading')
    permission_required = "ledger.delete_taxgroupheading"
    title = model._meta.verbose_name


class TaxItemGroupHeadingListView(PermissionRequiredMixin, generic.ListView):
    model = TaxItemGroupHeading
    template_name = "ledger/taxitemgroupheading_list.html"
    permission_required = "ledger.view_taxitemgroupheading"


class TaxItemGroupHeading_Json(custom.JSONResponseMixin):
    permission_required = "ledger.view_taxitemgroupheading"

    def get(self, request):
        taxitemgroup = TaxItemGroupHeading.objects.all()
        data = [d.get_data() for d in taxitemgroup]
        ret = {'data': data}
        return JsonResponse(ret)


class TaxItemGroupHeadingCreateView(custom.ObjectCreateView):
    model = TaxItemGroupHeading
    fields = '__all__'
    success_url = reverse_lazy('ledger:taxitemgroupheading')
    permission_required = "ledger.add_taxitemgroupheading"
    title = model._meta.verbose_name


class TaxItemGroupHeadingUpdateView(custom.ObjectUpdateView):
    model = TaxItemGroupHeading
    fields = '__all__'
    success_url = reverse_lazy('ledger:taxitemgroupheading')
    permission_required = "ledger.change_taxitemgroupheading"
    title = model._meta.verbose_name
    template_name = "common/offcanvas_form.html"


class TaxItemGroupHeadingDeleteView(custom.ObjectDeleteView):
    model = TaxItemGroupHeading
    success_url = reverse_lazy('ledger:taxitemgroupheading')
    permission_required = "ledger.delete_taxitemgroupheading"
    title = model._meta.verbose_name


class PaymTermListView(PermissionRequiredMixin, generic.ListView):
    model = PaymTerm
    template_name = "ledger/paymterm_list.html"
    permission_required = "ledger.view_paymterm"


class PaymTerm_Json(custom.JSONResponseMixin):
    permission_required = "ledger.view_paymterm"

    def get(self, request):
        taxitemgroup = PaymTerm.objects.all()
        data = [d.get_data() for d in taxitemgroup]
        ret = {'data': data}
        return JsonResponse(ret)


class PaymTermCreateView(custom.ObjectCreateView):
    model = PaymTerm
    fields = '__all__'
    success_url = reverse_lazy('ledger:paymterm')
    permission_required = "ledger.add_paymterm"
    title = model._meta.verbose_name


class PaymTermUpdateView(custom.ObjectUpdateView):
    model = PaymTerm
    fields = '__all__'
    success_url = reverse_lazy('ledger:paymterm')
    permission_required = "ledger.change_paymterm"
    title = model._meta.verbose_name
    template_name = "common/offcanvas_form.html"


class PaymTermDeleteView(custom.ObjectDeleteView):
    model = PaymTerm
    success_url = reverse_lazy('ledger:paymterm')
    permission_required = "ledger.delete_paymterm"
    title = model._meta.verbose_name

templates/ledger/offcanvas_form.html
{% load i18n widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" class="modal-content shadow-none" style="max-height: 100%; height: 100%;">
  <div class="offcanvas-header border-bottom">
    <h5 class="offcanvas-title"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;
    {% if object %} {% blocktranslate with object_t=object %} Edit {{ object_t }} {% endblocktranslate %} {% else %} {% blocktranslate %} Add {{ title }} {% endblocktranslate %} {% endif %} </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    {% for field in form %}
      <div class="mb-3">
          <label for="{{ field.id_for_label }}" class="form-label">{{ field.label_tag }}</label>
          {% if field|widget_type == 'selectmultiple' %}
            {% render_field field class="form-control select2" style="width: 100%" %} 
          {% else %}
            {% render_field field class="form-control" %}
          {% endif %}
          <div class="invalid-feedback">{{ field.errors|first }}</div>
          <div class="form-text" id="{{ field.auto_id }}_helptext">
           {{ field.help_text|safe }}
          </div>
      </div>
    {% endfor %}
  </div>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end border-top p-2">
    <button type="submit" class="btn btn-primary">{% translate 'Submit' %}</button>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="offcanvas">{% translate 'Cancel' %}</button>
  </div>
</form>
{% endwith %}
<script>
  $( '.select2' ).select2( {
    theme: "classic",
    dropdownParent: $('#offcanvas')
  } );

</script>

templates/ledger/paymterm_list.html
{% extends "layouts/base-datatable.html" %}
{% load i18n %}
{% load static %}

{% block stylesheets %}
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->

{% endblock stylesheets %}

{% block navigation %}
<nav class="navbar navbar-expand-sm fixed-top bg-light border shadow-sm rounded">
  <div class="container-fluid">
    <ul class="navbar-nav col-sm-6">
      {% if perms.ledger.add_paymterm %}  
      <li class="nav-item">
        <a hx-get="{% url 'ledger:paymterm-create' %}" accesskey="N" class="btn btn-sm btn-light nav-link" data-bs-toggle="offcanvas" hx-target="#offcanvas" 
        data-toggle="tooltip" data-bs-placement="bottom" data-bs-title= "New (Alt+N)">
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
        </a>
      </li>
      {% endif %}
      {% if perms.ledger.change_paymterm %}
      <li class="nav-item">
        <button type="button" id="btnEdit" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Edit' %} disabled>
          <i class="fa-solid fa-pen"></i>&nbsp;&nbsp;{% translate 'Edit' %}
        </button>
      </li>
      {% endif %}
      {% if perms.ledger.delete_paymterm %}
      <li class="nav-item">
        <button type="button" id="btnDel" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Delete' %} disabled>
          <i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;{% translate 'Delete' %}
        </button>
      </li>
      {% endif %}
      <li class="nav-item">
        <button type="button" id="btnrefresh" class="btn btn-sm btn-light nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Refresh' %} >
          <i class="fa-solid fa-arrows-rotate"></i>&nbsp;&nbsp;{% translate 'Refresh' %}
        </button>
      </li>
    </ul>
    <div class="col-sm-6 d-flex justify-content-end">
      <div class="btn-group" role="group" aria-label="related function">
      </div>
    </div>
  </div>
</nav>
{% endblock navigation %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            {% translate 'Tax codes'|title %} <i class="bi bi-0-circle-fill"></i>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="DataList" class="table table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                    <th>{% translate "Payment terms" %}</th>
                    <th>{% translate "Name" %}</th>
                    <th>{% translate "Payment method" %}</th>
                    <th>{% translate "Months" %}</th>
                    <th>{% translate "Weeks" %}</th>
                    <th>{% translate "Days" %}</th>
                  </tr>
              </thead>
            </table>
          </div> <!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>

    <!-- /.content -->
  </div>

  <!-- Placeholder for the offcanvas -->
  <div id="offcanvas" class="offcanvas offcanvas-end" aria-labelledby="offcanvasLabel" hx-target="this">
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>

{% endblock content %}  

{% block javascripts %}
<script>
$(document).ready(function(){    
  table = new DataTable('#DataList',{
      ajax: "{% url 'ledger:paymterm-json' %}",
      columns: [
          { data: 'code' },
          { data: 'name' },
          { data: 'paym_method' },
          { data: 'num_of_months' },
          { data: 'num_of_weeks' },
          { data: 'num_of_days' } 
      ],
      rowId: 'id',
      select: {
          style: 'single'
      },
      colReorder: true,
      "initComplete": function( settings, json ) {
                    htmx.process('#DataList');
      },
  });

  table
    .on('select', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').removeAttr("disabled");
    })
    .on('deselect', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').attr("disabled", "disabled");
    });

  document.body.addEventListener("reloadTable", function(evt){
    table.ajax.reload(function() {
        htmx.process('#DataList');
    }, false)
  });
  
  $("#btnEdit").click(function () {    
      var id = table.row({ selected: true }).id();
      doUpdate(id);
  });
  $("#btnDel").click(function () {    
      var id = table.row({ selected: true }).id();
      doDelete(id);
  });
  $("#btnrefresh").click(function () {    
      table.ajax.reload();
  });
})
</script>
<script>
function doUpdate(id) {
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'ledger:paymterm-update' 123 %}".replace(/123/, id.toString()), {target:'#offcanvas', swap:'innerHTML'});
}
function doDelete(id) {
  //window.location.href = "{% url 'group-delete' 123 %}".replace(/123/, id.toString())
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'ledger:paymterm-delete' 123 %}".replace(/123/, id.toString()), {target:'#dialog', swap:'innerHTML'});
}
</script>
{% endblock javascripts %}

templates/ledger/taxgroupheading_list.html
{% extends "layouts/base-datatable.html" %}
{% load i18n %}
{% load static %}

{% block stylesheets %}
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->
  <link rel="stylesheet" href="{% static 'dist/plugins/select2/css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/plugins/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css' %}">
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->
{% endblock stylesheets %}

{% block navigation %}
<nav class="navbar navbar-expand-sm fixed-top bg-light border shadow-sm rounded">
  <div class="container-fluid">
    <ul class="navbar-nav col-sm-6">
      {% if perms.ledger.add_taxgroupheading %}  
      <li class="nav-item">
        <a hx-get="{% url 'ledger:taxgroupheading-create' %}" accesskey="N" class="btn btn-sm btn-light nav-link text-sm-center" data-bs-toggle="offcanvas" hx-target="#offcanvas" 
        data-toggle="tooltip" data-bs-placement="bottom" data-bs-title= "New (Alt+N)">
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
        </a>
      </li>
      {% endif %}
      {% if perms.ledger.change_taxgroupheading %}
      <li class="nav-item">
        <button type="button" id="btnEdit" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Edit' %} disabled>
          <i class="fa-solid fa-pen"></i>&nbsp;&nbsp;{% translate 'Edit' %}
        </button>
      </li>
      {% endif %}
      {% if perms.ledger.delete_taxgroupheading %}
      <li class="nav-item">
        <button type="button" id="btnDel" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Delete' %} disabled>
          <i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;{% translate 'Delete' %}
        </button>
      </li>
      {% endif %}
      <li class="nav-item">
        <button type="button" id="btnrefresh" class="btn btn-sm btn-light nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Refresh' %} >
          <i class="fa-solid fa-arrows-rotate"></i>&nbsp;&nbsp;{% translate 'Refresh' %}
        </button>
      </li>
    </ul>
    <div class="col-sm-6 d-flex justify-content-end">
      <div class="btn-group" role="group" aria-label="related function">
      </div>
    </div>
  </div>
</nav>
{% endblock navigation %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            {% translate 'Tax group'|title %} <i class="bi bi-0-circle-fill"></i>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="DataList" class="table table-sm table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                    <th>{% translate "Tax group" %}</th>
                    <th>{% translate "Name" %}</th>
                    <th>{% translate "Tax code" %}</th>
                  </tr>
              </thead>
            </table>
          </div> <!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>

    <!-- /.content -->
  </div>

  <!-- Placeholder for the offcanvas -->
  <div id="offcanvas" class="offcanvas offcanvas-end" aria-labelledby="offcanvasLabel" hx-target="this">
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>

{% endblock content %}  

{% block javascripts %}
<script src="{% static 'dist/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'dist/plugins/select2/js/select2.min.js' %}"></script>
<script>
$(document).ready(function(){    
  table = new DataTable('#DataList',{
      ajax: "{% url 'ledger:taxgroupheading-json' %}",
      columns: [
          { data: 'tax_group' },
          { data: 'name' },
          { data: 'display_tax' },
      ],
      rowId: 'id',
      select: {
          style: 'single'
      },
      colReorder: true,
      "initComplete": function( settings, json ) {
                    htmx.process('#DataList');
      },
  });

  table
    .on('select', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').removeAttr("disabled");
    })
    .on('deselect', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').attr("disabled", "disabled");
    });

  document.body.addEventListener("reloadTable", function(evt){
    table.ajax.reload(function() {
        htmx.process('#DataList');
    }, false)
  });
  
  $("#btnEdit").click(function () {    
      var id = table.row({ selected: true }).id();
      doUpdate(id);
  });
  $("#btnDel").click(function () {    
      var id = table.row({ selected: true }).id();
      doDelete(id);
  });
  $("#btnrefresh").click(function () {    
      table.ajax.reload();
  });
})
</script>
<script>
function doUpdate(id) {
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'ledger:taxgroupheading-update' 123 %}".replace(/123/, id.toString()), {target:'#offcanvas', swap:'innerHTML'});
}
function doDelete(id) {
  //window.location.href = "{% url 'group-delete' 123 %}".replace(/123/, id.toString())
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'ledger:taxgroupheading-delete' 123 %}".replace(/123/, id.toString()), {target:'#dialog', swap:'innerHTML'});
}
</script>
{% endblock javascripts %}