apps/basic/urls.py
from django.urls import path
from . import views


app_name = "basic"
urlpatterns = [
    path('setup/country/', views.CountryListView.as_view(), name="country"),
    path('setup/country/create/', views.CountryCreateView.as_view(), name="country-create"),
    path('setup/countryjson/', views.CountryList_Json.as_view(), name="country-json"),
    path('setup/country/<int:pk>/update/', views.CountryUpdateView.as_view(), name="country-update"),
    path('setup/country/<int:pk>/delete/', views.CountryDeleteView.as_view(), name="country-delete"),
    path('setup/currency/', views.CurrencyListView.as_view(), name="currency"),
    path('setup/currency/create/', views.CurrencyCreateView.as_view(), name="currency-create"),
    path('setup/currencyjson/', views.CurrencyList_Json.as_view(), name="currency-json"),
    path('setup/currency/<int:pk>/update/', views.CurrencyUpdateView.as_view(), name="currency-update"),
    path('setup/currency/<int:pk>/delete/', views.CurrencyDeleteView.as_view(), name="currency-delete"),
    path('company/', views.CompanyInfoView.as_view(), name="company"),
    path('setup/companyaddress/<int:pk>/create/', views.create_companyaddress, name="companyaddress-create"),
    path('setup/companyaddress/<int:pk>/update/', views.update_companyaddress, name="companyaddress-update"),
    path('setup/companyaddress/<int:pk>/delete/', views.delete_companyaddress, name="companyaddress-delete"),
    path('setup/companyaddress/<int:pk>/', views.detail_companyaddress, name="companyaddress-detail"),
    path('setup/unit/', views.UnitListView.as_view(), name="unit"),
    path('setup/unit/create/', views.UnitCreateView.as_view(), name="unit-create"),
    path('setup/unitjson/', views.Unit_Json.as_view(), name="unit-json"),
    path('setup/unit/<int:pk>/update/', views.UnitUpdateView.as_view(), name="unit-update"),
    path('setup/unit/<int:pk>/delete/', views.UnitDeleteView.as_view(), name="unit-delete"),
    path('setup/unit/<int:pk>/unittext/', views.manage_unittext, name="unit-text"),
    path('setup/unitconvert/', views.UnitConvertListView.as_view(), name="unitconvert"),
    path('setup/unitconvert/create/', views.UnitConvertCreateView.as_view(), name="unitconvert-create"),
    path('setup/unitconvertjson/', views.UnitConvert_Json.as_view(), name="unitconvert-json"),
    path('setup/unitconvert/<int:pk>/update/', views.UnitConvertUpdateView.as_view(), name="unitconvert-update"),
    path('setup/unitconvert/<int:pk>/delete/', views.UnitConvertDeleteView.as_view(), name="unitconvert-delete"),
    path('setup/numbersequence/', views.NumberSequenceTableListView.as_view(), name="numbersequence"),
    path('setup/numbersequence/create/', views.NumberSequenceTableCreateView.as_view(), name="numbersequence-create"),
    path('setup/numbersequencejson/', views.NumberSequenceTable_Json.as_view(), name="numbersequence-json"),
    path('setup/numbersequence/<int:pk>/update/', views.NumberSequenceTableUpdateView.as_view(), name="numbersequence-update"),
    path('setup/numbersequence/<int:pk>/delete/', views.NumberSequenceTableDeleteView.as_view(), name="numbersequence-delete"),
    path('setup/dlvterm/', views.DlvTermListView.as_view(), name="dlvterm"),
    path('setup/dlvterm/create/', views.DlvTermCreateView.as_view(), name="dlvterm-create"),
    path('setup/dlvtermjson/', views.DlvTerm_Json.as_view(), name="dlvterm-json"),
    path('setup/dlvterm/<int:pk>/update/', views.DlvTermUpdateView.as_view(), name="dlvterm-update"),
    path('setup/dlvterm/<int:pk>/delete/', views.DlvTermDeleteView.as_view(), name="dlvterm-delete"),
    path('setup/dlvmode/', views.DlvModeListView.as_view(), name="dlvmode"),
    path('setup/dlvmode/create/', views.DlvModeCreateView.as_view(), name="dlvmode-create"),
    path('setup/dlvmodejson/', views.DlvMode_Json.as_view(), name="dlvmode-json"),
    path('setup/dlvmode/<int:pk>/update/', views.DlvModeUpdateView.as_view(), name="dlvmode-update"),
    path('setup/dlvmode/<int:pk>/delete/', views.DlvModeDeleteView.as_view(), name="dlvmode-delete"),
    path('setup/dlvdestination/', views.DlvDestinationListView.as_view(), name="dlvdestination"),
    path('setup/dlvdestination/create/', views.DlvDestinationCreateView.as_view(), name="dlvdestination-create"),
    path('setup/dlvdestinationjson/', views.DlvDestination_Json.as_view(), name="dlvdestination-json"),
    path('setup/dlvdestination/<int:pk>/update/', views.DlvDestinationUpdateView.as_view(), name="dlvdestination-update"),
    path('setup/dlvdestination/<int:pk>/delete/', views.DlvDestinationDeleteView.as_view(), name="dlvdestination-delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", include("apps.authentication.urls")), # Auth routes - login / register
    path('', include('authentication.urls')),
    path('', include('home.urls')),
    path('system/', include('system.urls')),
    path('basic/', include('basic.urls')),
    path('hrm/', include('hrm.urls')),
    path('ledger/', include('ledger.urls')),
    path('invent/', include('invent.urls')),
    path('vend/', include('vend.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handling the 404 error
handler404 = "system.views.error_404_view"

handler500 = "system.views.error_500_view"

handler403 = "system.views.error_403_view"

apps/basic/models.py
from django.db import models
from django.utils.translation import get_language, gettext_lazy as _
from system.models import Language
from django.core.exceptions import ObjectDoesNotExist


class CountryRegion(models.Model):
    code = models.CharField(max_length=2, unique=True, verbose_name=_('Country/region'))
    name = models.CharField(max_length=250)
    en_name = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('english name'))

    def __str__(self):
        return  "(%s) %s" % (self.code,self.name)


class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True, verbose_name=_('currency'))
    name = models.CharField(max_length=60)
    symbol = models.CharField(max_length=5, null=True, blank=True)

    def __str__(self):
        return  self.code


class CompanyInfo(models.Model):
    name = models.CharField(max_length=60, unique=True, verbose_name=_('company name'))
    en_name = models.CharField(max_length=60, null=True, blank=True, verbose_name=_('english name'))
    taxnum = models.CharField(max_length=18, null=True, blank=True, verbose_name=_('tax number'))
    address = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('address'))
    zipcode = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('Postal code'))
    countryregion = models.ForeignKey('CountryRegion', on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_('Country/region'))
    language = models.ForeignKey('system.Language', on_delete=models.SET_NULL, null=True, blank=True)
    currency = models.ForeignKey('Currency', on_delete=models.SET_NULL, null=True, blank=True)
    telephone = models.CharField(max_length=40, null=True, blank=True)
    telephoneext = models.CharField(max_length=10, null=True, blank=True, verbose_name=_('extension'))
    teleFax = models.CharField(max_length=40, null=True, blank=True)
    mobilephone = models.CharField(max_length=40, null=True, blank=True, verbose_name="mobile phone")
    email = models.EmailField(null=True, blank=True)
    url = models.URLField(null=True, blank=True, verbose_name="web site")

    def __str__(self):
        return self.name


class CompanyAddress(models.Model):
    NONE = "N"
    DELIVERY = "D"
    INVOICE = "I"
    PAYMENT = "P"
    OTHER = "O"
    TYPE_CHOICES = [
        (NONE, _('none')),
        (DELIVERY, _('delivery')),
        (INVOICE, _('invoice')),
        (PAYMENT, _('payment')),
        (OTHER, _('other')),
    ]

    company =  models.ForeignKey('CompanyInfo', on_delete=models.CASCADE)
    name = models.CharField(max_length=60, unique=True, verbose_name=_('name'))
    addresstype = models.CharField(max_length=2, choices=TYPE_CHOICES, default=NONE, null=True, blank=True, verbose_name=_('address type'))
    address = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('address'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("person title")
    

class Unit(models.Model):
    unit_id = models.CharField(max_length=5, unique=True, verbose_name=_("unit"))
    txt = models.CharField(_("name"), max_length=30, blank=True)
    unit_decimals = models.PositiveSmallIntegerField(_("decimals"), default=2)
    symbol = models.CharField(max_length=5, null=True, blank=True)

    class Meta:
        verbose_name = _("units")

    
    def __str__(self):
        return  self.unit_id

    
    def language_unit(self, unitid, languageid=get_language()):
        language = Language.objects.get(code=languageid)
        
        try:
            unit_txt = UnitTxt.objects.get(unit=self.id,language=language)
            return unit_txt.unitid_txt
        except ObjectDoesNotExist:
            return unitid


class UnitTxt(models.Model):
    unit = models.ForeignKey("Unit", on_delete=models.CASCADE)
    language = models.ForeignKey('system.Language', on_delete=models.SET_NULL, null=True, blank=True)
    unitid_txt = models.CharField(_("text"), max_length=10, blank=True)

    class Meta:
        verbose_name = _("unit texts")
        unique_together = ["unit", "language"]
    
    def __str__(self):
        return  self.unitid_txt


class UnitConvert(models.Model):
    HALF_UP = "O"
    UP = "U"
    DOWN = "D"
    ROUND_CHOICES = [
        (HALF_UP, _('round off')),
        (UP, _('up')),
        (DOWN, _('down')),
    ]

    from_unit = models.ForeignKey("Unit", on_delete=models.RESTRICT, blank=True, verbose_name=_("from unit"), related_name="from_unit")
    to_unit = models.ForeignKey("Unit",  on_delete=models.RESTRICT, blank=True, verbose_name=_("to unit"), related_name="to_unit")
    factor = models.DecimalField(max_digits=9, decimal_places=5)
    markup = models.DecimalField(_("additional quantity"), default=0, max_digits=5, decimal_places=2)
    round_off =  models.CharField(max_length=2, choices=ROUND_CHOICES, default=HALF_UP, verbose_name=_('round-off'))

    class Meta:
        verbose_name = _("unit conversion")
        unique_together = ["from_unit", "to_unit"]

    def __str__(self):
        return  self.from_unit.unit_id

     #JSON
    def get_data(self):
        return {
            'id': self.id,
            'from_unit': self.from_unit.unit_id,
            'to_unit': self.to_unit.unit_id,
            'factor': self.factor,
            'markup': self.markup,
            'round_off': self.get_round_off_display()
        }


class NumberSequenceTable(models.Model):
    number_code = models.CharField(_("number sequence code"), max_length=10, unique=True)
    txt = models.CharField(_("name"), max_length=30, blank=True)
    lowest = models.PositiveIntegerField(_("smallest"), default=1)
    highest = models.PositiveIntegerField(_("largest"))
    next_rec = models.PositiveIntegerField(_("next"), blank=True)
    num_format = models.CharField(_("format"), max_length=30, blank=True)

    class Meta:
        verbose_name = _("number sequence")

    def __str__(self):
        return self.number_code


""" Distribution models """
class DlvTerm(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Delivery terms"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    class Meta:
        verbose_name = _("Terms of delivery")

    def __str__(self):
        return self.code


class DlvMode(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Delivery Mode"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    class Meta:
        verbose_name = _("Mode of delivery")

    def __str__(self):
        return self.code

    
class DlvDestination(models.Model):
    code = models.CharField(max_length=10, unique=True, verbose_name=_("Destination code"))
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("Description"))

    class Meta:
        verbose_name = _("Destination of delivery")

    def __str__(self):
        return self.code
        

apps/basic/forms.py
from django.forms import ModelForm, TextInput, HiddenInput, Textarea
from django.forms import inlineformset_factory
from .models import CompanyInfo, CompanyAddress, UnitTxt, Unit
from django.utils.translation import gettext_lazy as _


class CompanyForm(ModelForm):
    class Meta:
        model = CompanyInfo
        fields = "__all__"
        widgets = {
            "address": Textarea(attrs={"rows": 3}),
        }


class CompanyAddressForm(ModelForm):
    class Meta:
        model = CompanyAddress
        fields = ["name","addresstype","address"]
        widgets = {
            "address": Textarea(attrs={"rows": 3}),
        }


UnitTxtFormset = inlineformset_factory(
    Unit, UnitTxt, fields=["language", "unitid_txt"], extra=1, can_delete=True
)

templates/basic/companyaddress_form.html
{% load i18n static widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}

<div hx-target="this" hx-swap="outerHTML" class="shadow-sm p-3 mb-5 bg-body-tertiary rounded" id="addressform">
    <form method="post">
        {% csrf_token %}
        <div class="row g-3">
            <div class="col-md-6">
                <label for="{{ addform.name.id_for_label }}" class="form-label">{% translate 'Name' %}</label>
                {% render_field addform.name class="form-control" %}
                <div class="invalid-feedback">{{ addform.name.errors|first }}</div>
            </div>
            <div class="col-md-6">
                <label for="{{ addform.addresstype.id_for_label }}" class="form-label">{% translate 'Type' %}</label>
                {% render_field addform.addresstype class="form-control" %}
                <div class="invalid-feedback">{{ addform.addresstype.errors|first }}</div>
            </div>
            <div class="col-12">
                <label for="{{ addform.address.id_for_label }}" class="form-label">{% translate 'Address' %}</label>
                {% render_field addform.address class="form-control" %}
                <div class="invalid-feedback">{{ addform.address.errors|first }}</div>
            </div>
            {% if companyaddress %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-primary btn-sm" hx-post="{% url 'basic:companyaddress-update' companyaddress.id %}">{% translate 'Submit' %}</button>
                <button type="button" class="btn btn-secondary btn-sm me-2" hx-get="{% url 'basic:companyaddress-detail' companyaddress.id %}">{% translate 'Cancel' %}</button>
            </div>
            {% else %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                {% if perms.basic.add_companyaddress %}
                <button type="submit" class="btn btn-primary btn-sm" hx-post="{% url 'basic:companyaddress-create' pk=company.id %}">{% translate 'Submit' %}</button>
                {% endif %}
                <button type="button" class="btn btn-secondary btn-sm me-2" onclick="closeForm()">{% translate 'Cancel' %}</button>
            </div>
            {% endif %}
        </div>
    </form>
</div>
{% endwith %}
<script>
function closeForm() {
  var divform = document.getElementById('addressform');
  divform.remove();
}
</script>

templates/basic/country_delete.html
{% load i18n %}
<form hx-post="{{ request.path }}" class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title"><i class="fa-solid fa-trash-can"></i>&nbsp;&nbsp;
    {% blocktranslate with object_t=object|title %} Delete {{ object_t }} {% endblocktranslate %}</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
     <p class="delete-text">{% translate 'Are you sure you want to delete ' %}
      <strong>{{ object }}</strong>?</p>
  </div>
  <div class="modal-footer flex-nowrap p-0">
    <button type="submit" class="btn btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">{% translate 'Confirm' %}</button>
    <button type="button" class="btn btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" data-bs-dismiss="modal">
      {% translate 'Cancel' %}
    </button>
  </div>
</form>

templates/basic/currency_list.html
{% extends "layouts/base-datatable.html" %}
{% load i18n %}
{% load static %}

{% block stylesheets %}
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->

{% endblock stylesheets %}

{% block navigation %}
<nav class="navbar navbar-expand-sm fixed-top bg-light border shadow-sm rounded">
  <div class="container-fluid">
    <ul class="navbar-nav col-sm-6">
      {% if perms.basic.add_currency %}
      <li class="nav-item">
        <a hx-get="{% url 'basic:currency-create' %}" accesskey="N" class="btn btn-sm btn-light nav-link" data-bs-toggle="offcanvas" hx-target="#offcanvas" 
        data-toggle="tooltip" data-bs-placement="bottom" data-bs-title= "New (Alt+N)">
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
        </a>
      </li>
      {% endif %}
      {% if perms.basic.change_currency %}
      <li class="nav-item">
        <button type="button" id="btnEdit" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Edit' %} disabled>
          <i class="fa-solid fa-pen"></i>&nbsp;&nbsp;{% translate 'Edit' %}
        </button>
      </li>
      {% endif %}
      {% if perms.basic.delete_currency %}
      <li class="nav-item">
        <button type="button" id="btnDel" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Delete' %} disabled>
          <i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;{% translate 'Delete' %}
        </button>
      </li>
      {% endif %}
      <li class="nav-item">
        <button type="button" id="btnrefresh" class="btn btn-sm btn-light nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Refresh' %} >
          <i class="fa-solid fa-arrows-rotate"></i>&nbsp;&nbsp;{% translate 'Refresh' %}
        </button>
      </li>
    </ul>
    <div class="col-sm-6 d-flex justify-content-end">
      <div class="btn-group" role="group" aria-label="related function"></div>
    </div>
  </div>
</nav>
{% endblock navigation %}

{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            {% translate 'Currency' %}
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="DataList" class="table table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                    <th>{% translate 'Currency' %}</th>
                    <th>{% translate 'Name' %}</th>
                    <th>{% translate 'Symbol' %}</th>
                  </tr>
              </thead>
            </table>
          </div> <!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>

    <!-- /.content -->
  </div>

  <!-- Placeholder for the offcanvas -->
  <div id="offcanvas" class="offcanvas offcanvas-end" aria-labelledby="offcanvasLabel" hx-target="this">
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>

{% endblock content %}  

{% block javascripts %}
<script>
$(document).ready(function(){    
  table = new DataTable('#DataList',{
      ajax: "{% url 'basic:currency-json' %}",
      columns: [
          { data: 'code' },
          { data: 'name' },
          { data: 'symbol' }
      ],
      rowId: 'id',
      select: {
          style: 'single'
      },
      colReorder: true,
      "initComplete": function( settings, json ) {
                    htmx.process('#DataList');
      },
  });

  table
    .on('select', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').removeAttr("disabled");
    })
    .on('deselect', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').attr("disabled", "disabled");
    });

  document.body.addEventListener("reloadTable", function(evt){
    table.ajax.reload(function() {
        htmx.process('#DataList');
    }, false)
  });
  
  $("#btnEdit").click(function () {    
      var id = table.row({ selected: true }).id();
      doUpdate(id);
  });
  $("#btnDel").click(function () {    
      var id = table.row({ selected: true }).id();
      doDelete(id);
  });
  $("#btnrefresh").click(function () {    
      table.ajax.reload();
  });
})
</script>
<script>
function doUpdate(id) {
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'basic:currency-update' 123 %}".replace(/123/, id.toString()), {target:'#offcanvas', swap:'innerHTML'});
}
function doDelete(id) {
  //window.location.href = "{% url 'group-delete' 123 %}".replace(/123/, id.toString())
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'basic:currency-delete' 123 %}".replace(/123/, id.toString()), {target:'#dialog', swap:'innerHTML'});
}
</script>
{% endblock javascripts %}

templates/basic/unit_list.html
{% extends "layouts/base-datatable.html" %}
{% load i18n %}
{% load static %}

{% block stylesheets %}
  <!-- overlayScrollbars -->
  <!--<link rel="stylesheet" href="{% static 'dist/plugins/overlayScrollbars/css/OverlayScrollbars_v2.min.css' %}">-->

{% endblock stylesheets %}

{% block navigation %}
<nav class="navbar navbar-expand-sm fixed-top bg-light border shadow-sm rounded">
  <div class="container-fluid">
    <ul class="navbar-nav col-sm-6">
      {% if perms.basic.add_unit %}  
      <li class="nav-item">
        <a hx-get="{% url 'basic:unit-create' %}" accesskey="N" class="btn btn-sm btn-light nav-link" data-bs-toggle="offcanvas" hx-target="#offcanvas" 
        data-toggle="tooltip" data-bs-placement="bottom" data-bs-title= "New (Alt+N)">
          <i class="fa-solid fa-plus"></i>&nbsp;&nbsp;{% translate 'New' %}
        </a>
      </li>
      {% endif %}
      {% if perms.basic.change_unit %}
      <li class="nav-item">
        <button type="button" id="btnEdit" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Edit' %} disabled>
          <i class="fa-solid fa-pen"></i>&nbsp;&nbsp;{% translate 'Edit' %}
        </button>
      </li>
      {% endif %}
      {% if perms.basic.delete_unit %}
      <li class="nav-item">
        <button type="button" id="btnDel" class="btn btn-light btn-sm nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Delete' %} disabled>
          <i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;{% translate 'Delete' %}
        </button>
      </li>
      {% endif %}
      <li class="nav-item">
        <button type="button" id="btnrefresh" class="btn btn-sm btn-light nav-link" data-toggle="tooltip" data-bs-placement="bottom" data-bs-title={% translate 'Refresh' %} >
          <i class="fa-solid fa-arrows-rotate"></i>&nbsp;&nbsp;{% translate 'Refresh' %}
        </button>
      </li>
    </ul>
    <div class="col-sm-6 d-flex justify-content-end">
      <div class="btn-group" role="group" aria-label="related function">
      </div>
    </div>
  </div>
</nav>
{% endblock navigation %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            {% translate 'units'|title %}
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="DataList" class="table table-striped table-bordered" style="width:100%">
              <thead>
                  <tr>
                    <th>{% translate "unit" %}</th>
                    <th>{% translate "name" %}</th>
                    <th>{% translate "decimals" %}</th>
                    <th>{% translate "symbol" %}</th>
                  </tr>
              </thead>
            </table>
          </div> <!-- /.card-body -->
        </div><!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>

    <!-- /.content -->
  </div>

  <!-- Placeholder for the offcanvas -->
  <div id="offcanvas" class="offcanvas offcanvas-end" aria-labelledby="offcanvasLabel" hx-target="this">
  </div>

  <!-- Placeholder for the modal -->
  <div id="modal" class="modal">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>

  <!-- Placeholder for the modal (item_txt) -->
  <div id="txtmodal" class="modal">
    <div id="txtdialog" class="modal-dialog modal-lg" hx-target="this"></div>
  </div>

{% endblock content %}  

{% block javascripts %}
<script src="{% static "dist/js/jquery.formset.js" %}"></script>
<script>
$(document).ready(function(){    
  table = new DataTable('#DataList',{
      ajax: "{% url 'basic:unit-json' %}",
      columns: [
          { data: 'unit_id',
            render: function (data, type, row) {
              let link = '{% url 'basic:unit-text' 123 %}'.replace(/123/, row.id);
              return data + '<a href="#" hx-get="' + link + '"' + 'class="d-none float-end" data-bs-toggle="modal" hx-target="#dialog" title="Unit Text"><i class="fa-solid fa-pen-to-square"></i></a>';
            }
          },
          { data: 'txt' } ,
          { data: 'unit_decimals' } ,
          { data: 'symbol' } 
      ],
      rowId: 'id',
      select: {
          style: 'single'
      },
      colReorder: true,
      "initComplete": function( settings, json ) {
                    htmx.process('#DataList');
      },
  });

  table
    .on('select', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').removeAttr("disabled");
    })
    .on('deselect', function (e, dt, type, indexes) {
      $('#btnEdit,#btnDel').attr("disabled", "disabled");
    });

  table
    .on( "mouseenter", "tbody tr", function() {
      $("a", this).removeClass("d-none");
    })
    .on( "mouseleave", "tbody tr", function() {
      $("a", this).addClass("d-none");
    } );

  document.body.addEventListener("reloadTable", function(evt){
    table.ajax.reload(function() {
        htmx.process('#DataList');
    }, false)
  });
  
  $("#btnEdit").click(function () {    
      var id = table.row({ selected: true }).id();
      doUpdate(id);
  });
  $("#btnDel").click(function () {    
      var id = table.row({ selected: true }).id();
      doDelete(id);
  });
  $("#btnrefresh").click(function () {    
      table.ajax.reload();
  });
})
</script>
<script>
function doUpdate(id) {
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'basic:unit-update' 123 %}".replace(/123/, id.toString()), {target:'#offcanvas', swap:'innerHTML'});
}
function doDelete(id) {
  //window.location.href = "{% url 'group-delete' 123 %}".replace(/123/, id.toString())
    // issue a GET to /example and replace #offcanvas with the response
  htmx.ajax('GET', "{% url 'basic:unit-delete' 123 %}".replace(/123/, id.toString()), {target:'#dialog', swap:'innerHTML'});
}
</script>
{% endblock javascripts %}